from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np

from .exceptions import DataValidationError


@dataclass(frozen=True)
class GeoBounds:
    west: float
    south: float
    east: float
    north: float

    def __post_init__(self) -> None:
        if self.west >= self.east or self.south >= self.north:
            raise DataValidationError("Bounds must satisfy west < east and south < north")


@dataclass(frozen=True)
class GridPoint:
    x: int
    y: int
    latitude: float | None = None
    longitude: float | None = None


@dataclass(frozen=True)
class Station:
    station_id: str
    latitude: float
    longitude: float
    name: str | None = None


@dataclass
class WindField:
    """Full-field velocity data for TurbSim/OpenFAST.

    ``velocity`` must use ``(time, vertical, lateral, component)`` order and
    contain three components in metres per second.
    """

    velocity: Any
    dy: float
    dz: float
    dt: float
    hub_height: float
    bottom_height: float
    description: str = "Generated by wrf-tools"
    mean_speed: float | None = None
    source: Path | None = None

    def __post_init__(self) -> None:
        array = np.asarray(self.velocity, dtype=float)
        if array.ndim != 4 or array.shape[-1] != 3:
            raise DataValidationError(
                "velocity must have shape (time, vertical, lateral, 3)"
            )
        if not np.all(np.isfinite(array)):
            raise DataValidationError("velocity contains NaN or infinite values")
        if min(self.dy, self.dz, self.dt) <= 0:
            raise DataValidationError("dy, dz, and dt must be positive")
        self.velocity = array
        if self.mean_speed is None:
            z_index = int(round((self.hub_height - self.bottom_height) / self.dz))
            z_index = min(max(z_index, 0), array.shape[1] - 1)
            y_index = array.shape[2] // 2
            self.mean_speed = float(np.mean(array[:, z_index, y_index, 0]))
