from __future__ import annotations

from typing import Any, Sequence

import numpy as np

from ...types import WindField


def wind_field_from_components(
    u: Any,
    v: Any,
    w: Any,
    *,
    time_axis: int,
    vertical_axis: int,
    lateral_axis: int,
    dy: float,
    dz: float,
    dt: float,
    hub_height: float,
    bottom_height: float,
    component_order: Sequence[str] = ("u", "v", "w"),
    component_signs: Sequence[float] = (1.0, 1.0, 1.0),
    reverse_vertical: bool = False,
    reverse_lateral: bool = False,
    description: str = "WRF-LES wind plane generated by wrf-tools",
) -> WindField:
    """Create a full-field wind plane from arbitrary WRF-LES array layouts.

    Axes are explicit because WRF extraction products do not share one fixed
    storage convention. ``component_order`` maps OpenFAST's longitudinal,
    lateral, and vertical components to the supplied WRF components.

    The result follows the TurbSim full-field convention consumed by
    OpenFAST/InflowWind. Verify that the extracted WRF plane is normal to the
    turbine inflow direction and that grid-relative WRF winds have been rotated
    when required. Format references: Jonkman (2009), *TurbSim User's Guide*,
    NREL/TP-500-46198; OpenFAST ``TurbSimFile`` reference implementation,
    https://github.com/OpenFAST/openfast_toolbox/blob/main/openfast_toolbox/io/turbsim_file.py.
    """
    components = {"u": np.asarray(u), "v": np.asarray(v), "w": np.asarray(w)}
    if set(component_order) != {"u", "v", "w"} or len(component_order) != 3:
        raise ValueError("component_order must be a permutation of ('u', 'v', 'w')")
    if len(component_signs) != 3:
        raise ValueError("component_signs must contain three values")
    target_axes = (time_axis, vertical_axis, lateral_axis)
    normalized: dict[str, np.ndarray] = {}
    for name, array in components.items():
        if array.ndim != 3:
            raise ValueError(f"{name} must be three-dimensional")
        normalized[name] = np.moveaxis(array, target_axes, (0, 1, 2))
    shapes = {array.shape for array in normalized.values()}
    if len(shapes) != 1:
        raise ValueError(f"Velocity component shapes differ: {sorted(shapes)}")
    velocity = np.stack(
        [normalized[name] * sign for name, sign in zip(component_order, component_signs)],
        axis=-1,
    )
    if reverse_vertical:
        velocity = velocity[:, ::-1, :, :]
    if reverse_lateral:
        velocity = velocity[:, :, ::-1, :]
    return WindField(
        velocity=velocity,
        dy=dy,
        dz=dz,
        dt=dt,
        hub_height=hub_height,
        bottom_height=bottom_height,
        description=description,
    )
